version: "3"
volumes:
  html-data:
    driver: local
  db-data:
    driver: local
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  wordpress:
    build: wordpress
    volumes:
      - html-data:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
  web:
    build: nginx
    volumes:
      - html-data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "8080:80"
